language: r
r:
  - oldrel
  - release
  - devel
os:
  - osx
  - linux
cache: packages
warnings_are_errors: true
r_check_args: "--no-manual --timings"

bioc_packages:
    - BiocStyle
    - SingleCellExperiment

env:
 global:
   - _R_CHECK_FORCE_SUGGESTS_: false
   - _R_CHECK_LENGTH_1_CONDITION_: verbose
   - _R_CHECK_LENGTH_1_LOGIC2_: verbose

notifications:
  email:
    on_success: change
    on_failure: change
